[tool.isort]
profile = "black"

[tool.codespell]
skip = 'package-lock.json,./node_modules'

[tool.bandit]
exclude = [".venv/*.*"]
exclude_dirs = [".venv", "node_modules"]
tests = ["B108", "B306", "B307", "B313", "B314", "B315", "B316", "B317", "B318", "B319", "B320", "B602", "B604"]

[tool.rstcheck]
report_level = "WARNING"

[tool.pydocstyle]
match-dir='[^node_module].*'

[tool.pylint.main]
py-version = "3.10"
jobs = 2
ignore-paths = ["^functions\\\\.venv\\\\.*$|^functions/.venv/.*$"]
